[tool.poetry]
name = "git-publish"
version = "0.1.0"
description = ""
authors = ["Warren Seine <warren.seine@onfido.com>"]
readme = "README.md"
packages = [
    { include = "gp" },
]

[tool.poetry.dependencies]
python = "^3.13"
pre-commit = "^4.1.0"
gitpython = "^3.1.41"
python-dotenv = "^1.0.0"
python-gitlab = "^5.6.0"
pygithub = "^2.1.1"
giturlparse = "^0.12.0"
ruff = "^0.9.9"
pyright = "^1.1.348"

[tool.poetry.scripts]
gp = "gp.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
